# Generated by Django 5.2.9 on 2026-01-02 19:20

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='file-text', help_text='Icona Lucide (es: newspaper, message-square, book-open)', max_length=50, verbose_name='Icona')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Categoria articolo',
                'verbose_name_plural': 'Categorie articoli',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
            ],
            options={
                'verbose_name': 'Pagina Indice Articoli',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Breve descrizione per SEO e anteprime', max_length=300, verbose_name='Sottotitolo')),
                ('body', wagtail.fields.RichTextField(verbose_name='Contenuto')),
                ('reading_time', models.PositiveIntegerField(default=1, help_text='Calcolato automaticamente al salvataggio', verbose_name='Tempo di lettura (min)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.articlecategory', verbose_name='Categoria')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine copertina')),
                ('service_areas', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='articles', to='services.servicearea', verbose_name='Aree di pratica')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
            },
            bases=('wagtailcore.page',),
        ),
    ]
