# Generated by Django 5.2.9 on 2026-01-03 09:50

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('services', '0002_rename_aree_attivita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='service_areas',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='articles', to='services.servicearea', verbose_name='Aree di attività'),
        ),
    ]
