# Generated by Django 5.2.9 on 2026-01-02 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(default='Studio Legale', help_text='Es: Studio Legale Rossi', max_length=200, verbose_name='Nome Studio')),
                ('lawyer_name', models.CharField(default='Avv. Mario Rossi', help_text='Nome completo con titolo', max_length=200, verbose_name='Nome Avvocato')),
                ('email', models.EmailField(default='info@example.com', max_length=254, verbose_name='Email')),
                ('email_pec', models.EmailField(default='avvocato@pec.it', max_length=254, verbose_name='PEC')),
                ('phone', models.CharField(default='+39 06 12345678', max_length=30, verbose_name='Telefono')),
                ('mobile_phone', models.CharField(blank=True, help_text='Opzionale - visibile solo se compilato', max_length=30, verbose_name='Cellulare')),
                ('address', models.CharField(default='Via Roma, 1 - 00100 Roma', max_length=300, verbose_name='Indirizzo')),
                ('city', models.CharField(default='Roma', max_length=100, verbose_name='Città')),
                ('maps_url', models.URLField(default='https://maps.apple.com/?daddr=41.9028,12.4964', help_text='Link Apple Maps o Google Maps', verbose_name='URL Mappa')),
                ('maps_lat', models.DecimalField(decimal_places=6, default=41.902782, max_digits=10, verbose_name='Latitudine')),
                ('maps_lng', models.DecimalField(decimal_places=6, default=12.496366, max_digits=10, verbose_name='Longitudine')),
                ('website', models.CharField(default='www.example.com', max_length=200, verbose_name='Sito Web')),
                ('facebook_url', models.URLField(blank=True, help_text='URL completo della pagina Facebook', verbose_name='Facebook')),
                ('twitter_handle', models.CharField(blank=True, help_text='Es: @avvocato', max_length=50, verbose_name='Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('jitsi_room_prefix', models.CharField(default='StudioLegale', help_text='Prefisso per le stanze videochiamata (senza spazi)', max_length=50, verbose_name='Prefisso stanza Jitsi')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('booking_price_cents', models.PositiveIntegerField(default=6000, help_text='ℹ️ Prezzo in centesimi: 6000 = €60,00', verbose_name='Prezzo consulenza (centesimi)')),
                ('booking_slot_duration', models.PositiveIntegerField(default=30, help_text='Durata di ogni slot prenotabile in minuti', verbose_name='Durata slot (minuti)')),
                ('email_from_address', models.CharField(blank=True, help_text="ℹ️ Formato: 'Studio Legale <info@example.com>'", max_length=200, verbose_name='Email mittente')),
                ('email_host', models.CharField(blank=True, help_text='ℹ️ Esempio: smtp.gmail.com, smtp.office365.com, smtp.tuoserver.it', max_length=200, verbose_name='Server SMTP')),
                ('email_host_password', models.CharField(blank=True, help_text="ℹ️ Per Gmail con 2FA: usa 'Password per le app' da Sicurezza account", max_length=200, verbose_name='Password SMTP')),
                ('email_host_user', models.CharField(blank=True, help_text="ℹ️ Solitamente l'indirizzo email completo", max_length=200, verbose_name='Username SMTP')),
                ('email_port', models.PositiveIntegerField(default=587, help_text='ℹ️ Porte comuni: 587 (TLS), 465 (SSL), 25 (non criptata)', verbose_name='Porta SMTP')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Attiva per connessione sicura (raccomandato)', verbose_name='Usa TLS')),
                ('ga4_measurement_id', models.CharField(blank=True, help_text='ℹ️ Trova in: Google Analytics → Admin → Data Streams → Measurement ID (G-XXXXXXXXXX)', max_length=50, verbose_name='Google Analytics 4 ID')),
                ('google_calendar_cache_ttl', models.PositiveIntegerField(default=600, help_text='Durata cache eventi calendario. Default: 600 = 10 minuti', verbose_name='Cache Google Calendar (secondi)')),
                ('google_calendar_ical_url', models.URLField(blank=True, help_text='ℹ️ Trova in: Google Calendar → Impostazioni → Integra calendario → Indirizzo segreto in formato iCal', verbose_name='Google Calendar iCal URL')),
                ('matomo_site_id', models.CharField(blank=True, help_text='ℹ️ Trova in: Matomo → Impostazioni → Siti Web → ID del sito', max_length=10, verbose_name='Matomo Site ID')),
                ('matomo_url', models.URLField(blank=True, help_text='ℹ️ URL della tua installazione Matomo (es: https://matomo.example.com)', verbose_name='Matomo URL')),
                ('payment_mode', models.CharField(choices=[('demo', 'Demo (simulato)'), ('sandbox', 'Sandbox (test)'), ('live', 'Live (produzione)')], default='demo', help_text='ℹ️ Demo: simula pagamenti (per sviluppo). Sandbox: usa chiavi di test Stripe/PayPal. Live: pagamenti reali.', max_length=10, verbose_name='Modalità pagamento')),
                ('paypal_client_id', models.CharField(blank=True, help_text='ℹ️ Trova in: PayPal Developer → My Apps & Credentials → App → Client ID', max_length=200, verbose_name='PayPal Client ID')),
                ('paypal_client_secret', models.CharField(blank=True, help_text='ℹ️ Trova in: PayPal Developer → My Apps & Credentials → App → Secret. MAI condividere!', max_length=200, verbose_name='PayPal Client Secret')),
                ('stripe_public_key', models.CharField(blank=True, help_text='ℹ️ Trova in: Stripe Dashboard → Developers → API Keys → Publishable key (pk_test_... o pk_live_...)', max_length=200, verbose_name='Stripe Public Key')),
                ('stripe_secret_key', models.CharField(blank=True, help_text='ℹ️ Trova in: Stripe Dashboard → Developers → API Keys → Secret key (sk_test_... o sk_live_...). MAI condividere!', max_length=200, verbose_name='Stripe Secret Key')),
                ('stripe_webhook_secret', models.CharField(blank=True, help_text='ℹ️ Trova in: Stripe Dashboard → Developers → Webhooks → Signing secret (whsec_...). Serve per confermare pagamenti.', max_length=200, verbose_name='Stripe Webhook Secret')),
            ],
            options={
                'verbose_name': 'Impostazioni Studio',
                'verbose_name_plural': 'Impostazioni Studio',
            },
        ),
    ]
