# Generated by Django 5.2.9 on 2026-01-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0003_sitesettings_domiciliazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text='Testo completo della Privacy Policy. Usa HTML per la formattazione. Le variabili {{studio_name}}, {{lawyer_name}}, {{address}}, {{email}}, {{email_pec}}, {{phone}} verranno sostituite automaticamente.', verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_conditions',
            field=models.TextField(blank=True, help_text='Testo completo dei Termini e Condizioni. Usa HTML per la formattazione. Le variabili {{studio_name}}, {{lawyer_name}}, {{address}}, {{email}}, {{email_pec}}, {{phone}}, {{website}} verranno sostituite automaticamente.', verbose_name='Termini e Condizioni'),
        ),
    ]
