# Generated by Django 5.2.9 on 2026-01-02 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0004_sitesettings_legal_pages'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Icona del sito (ICO, PNG 32x32 o SVG)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text='Testo completo della Privacy Policy. Usa HTML per la formattazione. Le variabili {{studio_name}}, {{lawyer_name}}, {{address}}, {{city}}, {{email}}, {{email_pec}}, {{phone}} verranno sostituite automaticamente.', verbose_name='Privacy Policy'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='terms_conditions',
            field=models.TextField(blank=True, help_text='Testo completo dei Termini e Condizioni. Usa HTML per la formattazione. Le variabili {{studio_name}}, {{lawyer_name}}, {{address}}, {{city}}, {{email}}, {{email_pec}}, {{phone}} verranno sostituite automaticamente.', verbose_name='Termini e Condizioni'),
        ),
    ]
