# Generated by Django 5.2.9 on 2026-01-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0005_sitesettings_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_lat',
            field=models.CharField(default='41.902782', help_text='Es: 41.902782 (puoi usare sia punto che virgola)', max_length=20, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_lng',
            field=models.CharField(default='12.496366', help_text='Es: 12.496366 (puoi usare sia punto che virgola)', max_length=20, verbose_name='Longitudine'),
        ),
    ]
