# Generated by Django 5.2.9 on 2026-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0005_sitesettings_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_lat',
            field=models.DecimalField(decimal_places=6, default=41.902782, help_text='Usa il punto come separatore decimale (es: 41.902782)', max_digits=10, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_lng',
            field=models.DecimalField(decimal_places=6, default=12.496366, help_text='Usa il punto come separatore decimale (es: 12.496366)', max_digits=10, verbose_name='Longitudine'),
        ),
    ]
