# Generated by Django 5.2.9 on 2026-01-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0006_alter_sitesettings_maps_lat_and_more'),
        ('sld_project', '0006_coordinates_to_charfield'),
    ]

    operations = [
    ]
