# Generated by Django 5.2.9 on 2026-01-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0007_merge_20260102_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter_handle',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='x_url',
            field=models.URLField(blank=True, help_text='URL completo del profilo X (es: https://x.com/nomeutente)', verbose_name='X (ex Twitter)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_lat',
            field=models.CharField(default='41.902782', help_text='Es: 41.902782 (puoi usare sia punto che virgola)', max_length=20, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_lng',
            field=models.CharField(default='12.496366', help_text='Es: 12.496366 (puoi usare sia punto che virgola)', max_length=20, verbose_name='Longitudine'),
        ),
    ]
