# Generated by Django 5.2.9 on 2026-01-02 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0008_twitter_to_x_url'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_social_image',
            field=models.ForeignKey(blank=True, help_text='Immagine 1200x630 px per condivisioni social (Facebook, Twitter, LinkedIn). Usata come fallback se la pagina non ha immagine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine Social Default'),
        ),
    ]
