# Generated by Django 5.2.9 on 2026-01-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0009_add_default_social_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='province',
            field=models.CharField(default='Lazio', help_text='Provincia o regione per SEO (es: Puglia, Lazio, Lombardia)', max_length=100, verbose_name='Provincia/Regione'),
        ),
    ]
