# Generated by Django 5.2.9 on 2026-01-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0010_add_province_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Indirizzo completo con CAP (es: Via Roma, 1 - 00100 Roma)', max_length=300, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='booking_slot_duration',
            field=models.PositiveIntegerField(default=30, help_text='Valori consigliati: 15, 30, 45 o 60 minuti', verbose_name='Durata slot (minuti)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Solo il nome della città (es: Roma, Milano, Bari)', max_length=100, verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email principale visibile ai clienti (es: info@studiolegalrossi.it)', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_pec',
            field=models.EmailField(blank=True, default='', help_text='PEC per comunicazioni ufficiali (es: avvocato.rossi@pec.ordineavvocati.it)', max_length=254, verbose_name='PEC'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL completo (es: https://facebook.com/studiolegalrossi)', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='jitsi_room_prefix',
            field=models.CharField(default='StudioLegale', help_text='Solo lettere senza spazi. Crea stanze tipo: StudioLegale_Mario_20260102', max_length=50, verbose_name='Prefisso stanza Jitsi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL completo (es: https://linkedin.com/in/mariorossi)', verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_lat',
            field=models.CharField(blank=True, default='', help_text="Clicca destro su Google Maps → 'Cosa c'è qui?' per vedere le coordinate (es: 41.902782)", max_length=20, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_lng',
            field=models.CharField(blank=True, default='', help_text='Seconda coordinata dopo la virgola (es: 12.496366)', max_length=20, verbose_name='Longitudine'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_url',
            field=models.URLField(blank=True, default='', help_text="Copia il link 'Condividi' da Google Maps o Apple Maps", verbose_name='URL Mappa'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Formato internazionale: +39 06 1234567', max_length=30, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='website',
            field=models.CharField(blank=True, default='', help_text='Senza https:// (es: www.studiolegalrossi.it)', max_length=200, verbose_name='Sito Web'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='x_url',
            field=models.URLField(blank=True, help_text='URL completo (es: https://x.com/avvrossi)', verbose_name='X (ex Twitter)'),
        ),
    ]
