# Generated by Django 5.2.9 on 2026-01-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0011_improve_help_texts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='google_calendar_ical_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='paypal_client_secret',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='stripe_secret_key',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='stripe_webhook_secret',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='jitsi_room_prefix',
            field=models.CharField(default='StudioLegale', help_text='Solo lettere senza spazi. Il link finale sarà: meet.jit.si/Prefisso-[codice casuale a 16 caratteri]', max_length=50, verbose_name='Prefisso stanza Jitsi'),
        ),
    ]
