# Generated by Django 5.2.9 on 2026-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0013_change_logo_favicon_to_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent',
            field=models.CharField(default='#e91e63', help_text='Colore principale del brand per CTA, link e decorazioni (formato HEX: #000000)', max_length=7, verbose_name='Colore Accento'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_black',
            field=models.CharField(default='#0a0a0a', help_text='Colore nero principale per testi e sfondi scuri (formato HEX: #000000)', max_length=7, verbose_name='Colore Nero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_dark',
            field=models.CharField(default='#1a1a1a', help_text='Grigio scuro per elementi secondari (formato HEX: #000000)', max_length=7, verbose_name='Colore Scuro'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_gray',
            field=models.CharField(default='#6b7280', help_text='Grigio per testi secondari (formato HEX: #000000)', max_length=7, verbose_name='Colore Grigio'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_silver',
            field=models.CharField(default='#f5f5f5', help_text='Sfondo chiaro per sezioni alternate (formato HEX: #000000)', max_length=7, verbose_name='Colore Argento'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_white',
            field=models.CharField(default='#ffffff', help_text='Bianco per sfondi e testi chiari (formato HEX: #000000)', max_length=7, verbose_name='Colore Bianco'),
        ),
    ]
