# Generated by Django 5.2.9 on 2026-01-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0014_add_brand_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent_hover',
            field=models.CharField(default='#be185d', help_text='Colore accento al passaggio del mouse, tipicamente più scuro (formato HEX: #000000)', max_length=7, verbose_name='Colore Accento Hover'),
        ),
    ]
