# Generated by Django 5.2.9 on 2026-01-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0015_add_color_accent_hover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='paypal_client_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='stripe_public_key',
        ),
    ]
