# Generated by Django 5.2.9 on 2026-01-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sld_project', '0016_remove_payment_fields_from_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cap',
            field=models.CharField(blank=True, default='', help_text='Codice di Avviamento Postale (es: 73100)', max_length=10, verbose_name='CAP'),
        ),
    ]
