# Generated by Django 5.2.9 on 2026-01-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='address_martina',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='martina_lat',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='martina_lng',
        ),
    ]
