# Generated by Django 5.2.9 on 2026-01-01 21:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Es: scale, gavel, shield', max_length=50, verbose_name='Icona')),
                ('short_description', models.TextField(max_length=300, verbose_name='Descrizione breve')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Area di pratica',
                'verbose_name_plural': 'Aree di pratica',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
            ],
            options={
                'verbose_name': 'Pagina Aree di Pratica',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Sottotitolo')),
                ('body', wagtail.fields.RichTextField(verbose_name='Contenuto')),
                ('service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='services.servicearea')),
            ],
            options={
                'verbose_name': 'Pagina Servizio',
            },
            bases=('wagtailcore.page',),
        ),
    ]
