# Generated by Django 5.2.9 on 2026-01-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Area di attività', 'verbose_name_plural': 'Aree di attività'},
        ),
        migrations.AlterModelOptions(
            name='servicesindexpage',
            options={'verbose_name': 'Pagina Aree di Attività'},
        ),
    ]
