# Generated by Django 5.2.9 on 2026-01-01 15:00

from django.db import migrations, models


def add_mediazione_service(apps, schema_editor):
    ServiceArea = apps.get_model('services', 'ServiceArea')
    
    # Conta i servizi esistenti per determinare l'ordine
    max_order = ServiceArea.objects.aggregate(models.Max('order'))['order__max'] or 0
    
    ServiceArea.objects.get_or_create(
        slug='mediazione-negoziazione',
        defaults={
            'name': 'Mediazione e Negoziazione Assistita',
            'icon': 'handshake',
            'short_description': 'Strumenti ADR per risolvere le controversie in modo rapido, economico e riservato, con pieno valore legale ed evitando i tempi del tribunale.',
            'order': max_order + 1,
        }
    )


def remove_mediazione_service(apps, schema_editor):
    ServiceArea = apps.get_model('services', 'ServiceArea')
    ServiceArea.objects.filter(slug='mediazione-negoziazione').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_mediazione_service, remove_mediazione_service),
    ]
