# Generated by Django 5.2.9 on 2026-01-01 15:02

from django.db import migrations


def remove_privacy_gdpr(apps, schema_editor):
    ServiceArea = apps.get_model('services', 'ServiceArea')
    ServiceArea.objects.filter(slug='privacy-gdpr').delete()


def restore_privacy_gdpr(apps, schema_editor):
    ServiceArea = apps.get_model('services', 'ServiceArea')
    ServiceArea.objects.get_or_create(
        slug='privacy-gdpr',
        defaults={
            'name': 'Privacy e GDPR',
            'icon': 'shield',
            'short_description': 'Consulenza in materia di protezione dei dati personali.',
            'order': 8,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_mediazione_service'),
    ]

    operations = [
        migrations.RunPython(remove_privacy_gdpr, restore_privacy_gdpr),
    ]
