# Generated by Django 5.2.9 on 2026-01-01 15:18

from django.db import migrations


def add_mediazione_page(apps, schema_editor):
    """Crea la ServicePage per Mediazione e Negoziazione Assistita."""
    ServicePage = apps.get_model('services', 'ServicePage')
    ServiceArea = apps.get_model('services', 'ServiceArea')
    ServicesIndexPage = apps.get_model('services', 'ServicesIndexPage')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Verifica se la pagina esiste già
    if ServicePage.objects.filter(slug='mediazione-negoziazione').exists():
        return
    
    # Trova la ServiceArea
    try:
        sa = ServiceArea.objects.get(slug='mediazione-negoziazione')
    except ServiceArea.DoesNotExist:
        return
    
    # Trova la pagina parent
    index = ServicesIndexPage.objects.first()
    if not index:
        return
    
    # Content type per ServicePage
    ct = ContentType.objects.get_for_model(ServicePage)
    
    body = '''<p>La mediazione e la negoziazione assistita rappresentano strumenti di risoluzione alternativa delle controversie (ADR) fondamentali nel panorama giuridico attuale, potenziati dalla recente Riforma Cartabia.</p>

<p>La <strong>mediazione civile e commerciale</strong> consente alle parti di raggiungere un accordo con l'ausilio di un mediatore imparziale. È obbligatoria per numerose materie, tra cui: condominio, diritti reali, divisioni, successioni, patti di famiglia, locazioni, comodato, affitto di aziende, risarcimento danni da responsabilità sanitaria e diffamazione, contratti assicurativi, bancari e finanziari.</p>

<p><em>L'obbligo è stato recentemente esteso anche a contratti di opera, somministrazione, subfornitura, franchising, consorzio, società di persone e reti di imprese.</em></p>

<p>La <strong>negoziazione assistita</strong> prevede che le parti, assistite dai propri avvocati, cooperino per raggiungere un accordo amichevole. L'accordo sottoscritto, certificato dai legali, costituisce titolo esecutivo (equiparato a una sentenza).</p>

<p>La procedura è condizione di procedibilità per le controversie in materia di risarcimento danni da circolazione di veicoli e natanti e per le domande di pagamento (a qualsiasi titolo) di somme non superiori a 50.000 euro (salvo i casi già soggetti a mediazione).</p>

<p>Lo Studio offre assistenza qualificata in tutte le fasi: dalla valutazione preliminare di convenienza (fiscale e procedurale), alla gestione delle sessioni, fino alla redazione formale degli accordi conciliativi.</p>

<p>L'approccio conciliativo permette di ottenere soluzioni rapide, preservare i rapporti commerciali o personali e beneficiare delle agevolazioni fiscali previste dalla legge.</p>'''

    # Calcola path e depth
    new_path = index.path + '0001'  # Placeholder, verrà corretto
    new_depth = index.depth + 1
    
    # Trova il prossimo path disponibile
    from django.db.models import Max
    last_child = ServicePage.objects.filter(path__startswith=index.path, depth=new_depth).aggregate(Max('path'))
    if last_child['path__max']:
        # Incrementa l'ultimo path
        last_num = int(last_child['path__max'][-4:])
        new_path = index.path + str(last_num + 1).zfill(4)
    else:
        new_path = index.path + '0001'
    
    page = ServicePage.objects.create(
        title='Mediazione e Negoziazione Assistita',
        slug='mediazione-negoziazione',
        path=new_path,
        depth=new_depth,
        service_area=sa,
        subtitle='Risoluzione alternativa delle controversie',
        body=body,
        content_type=ct,
        live=True,
        has_unpublished_changes=False,
        url_path=index.url_path + 'mediazione-negoziazione/',
    )
    
    # Aggiorna numchild del parent
    index.numchild = index.numchild + 1
    index.save()


def remove_mediazione_page(apps, schema_editor):
    ServicePage = apps.get_model('services', 'ServicePage')
    ServicePage.objects.filter(slug='mediazione-negoziazione').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_privacy_gdpr'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(add_mediazione_page, remove_mediazione_page),
    ]
