# Generated by Django 5.2.9 on 2025-12-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome regola')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')], verbose_name='Giorno della settimana')),
                ('start_time', models.TimeField(verbose_name='Ora inizio')),
                ('end_time', models.TimeField(verbose_name='Ora fine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Regola di disponibilità',
                'verbose_name_plural': 'Regole di disponibilità',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Data bloccata',
                'verbose_name_plural': 'Date bloccate',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Ora')),
                ('status', models.CharField(choices=[('pending', 'In attesa di pagamento'), ('confirmed', 'Confermato'), ('cancelled', 'Annullato'), ('completed', 'Completato')], default='pending', max_length=20, verbose_name='Stato')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importo pagato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appuntamento',
                'verbose_name_plural': 'Appuntamenti',
                'ordering': ['-date', '-time'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
