# Generated by Django 5.2.9 on 2026-01-01 21:38

import booking.models
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('booking', '0001_initial'), ('booking', '0002_appointment_payment_method_and_more'), ('booking', '0003_appointmentattachment'), ('booking', '0004_add_consultation_type_and_videocall'), ('booking', '0005_google_calendar_event'), ('booking', '0005_alter_appointment_notes'), ('booking', '0006_merge_20260101_1835'), ('booking', '0007_add_slot_count')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome regola')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')], verbose_name='Giorno della settimana')),
                ('start_time', models.TimeField(verbose_name='Ora inizio')),
                ('end_time', models.TimeField(verbose_name='Ora fine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Regola di disponibilità',
                'verbose_name_plural': 'Regole di disponibilità',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Data bloccata',
                'verbose_name_plural': 'Date bloccate',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('notes', models.TextField(verbose_name='Note')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Ora')),
                ('status', models.CharField(choices=[('pending', 'In attesa di pagamento'), ('confirmed', 'Confermato'), ('cancelled', 'Annullato'), ('completed', 'Completato')], default='pending', max_length=20, verbose_name='Stato')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importo pagato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Carta di credito (Stripe)'), ('paypal', 'PayPal')], default='stripe', max_length=20, verbose_name='Metodo pagamento')),
                ('paypal_payment_id', models.CharField(blank=True, max_length=255)),
                ('consultation_type', models.CharField(choices=[('in_person', 'In presenza'), ('video', 'Videochiamata')], default='in_person', max_length=20, verbose_name='Tipo consulenza')),
                ('videocall_code', models.CharField(blank=True, max_length=32, verbose_name='Codice videochiamata')),
                ('slot_count', models.PositiveIntegerField(default=1, help_text='Numero di slot consecutivi da 30 minuti', verbose_name='Numero slot')),
            ],
            options={
                'verbose_name': 'Appuntamento',
                'verbose_name_plural': 'Appuntamenti',
                'ordering': ['-date', '-time'],
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_uid', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='UID Google')),
                ('summary', models.CharField(max_length=255, verbose_name='Titolo')),
                ('start_datetime', models.DateTimeField(verbose_name='Inizio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fine')),
                ('synced_at', models.DateTimeField(verbose_name='Ultima sincronizzazione')),
            ],
            options={
                'verbose_name': 'Evento Google Calendar',
                'verbose_name_plural': 'Eventi Google Calendar',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=booking.models.appointment_attachment_path, verbose_name='File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome file originale')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Caricato il')),
                ('appointment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='booking.appointment', verbose_name='Appuntamento')),
            ],
            options={
                'verbose_name': 'Allegato',
                'verbose_name_plural': 'Allegati',
            },
        ),
    ]
