# Generated by Django 5.2.9 on 2026-01-03 09:50

import booking.models
import sld_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentattachment',
            name='file',
            field=models.FileField(upload_to=booking.models.appointment_attachment_path, validators=[sld_project.validators.FileValidator(allowed_extensions={'.doc': 'application/msword', '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', '.jpeg': 'image/jpeg', '.jpg': 'image/jpeg', '.odt': 'application/vnd.oasis.opendocument.text', '.pdf': 'application/pdf', '.png': 'image/png', '.rtf': 'application/rtf', '.tif': 'image/tiff', '.tiff': 'image/tiff', '.txt': 'text/plain', '.zip': 'application/zip'}, max_size=20971520)], verbose_name='File'),
        ),
    ]
