# Generated by Django 5.2.9 on 2025-12-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Carta di credito (Stripe)'), ('paypal', 'PayPal')], default='stripe', max_length=20, verbose_name='Metodo pagamento'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
