# Generated by Django 5.2.9 on 2026-01-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_aree_attivita'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Token pagamento'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID Rimborso'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data rimborso'),
        ),
    ]
