# Generated by Django 5.2.9 on 2025-12-31 10:52

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=booking.models.appointment_attachment_path, verbose_name='File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome file originale')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Caricato il')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='booking.appointment', verbose_name='Appuntamento')),
            ],
            options={
                'verbose_name': 'Allegato',
                'verbose_name_plural': 'Allegati',
            },
        ),
    ]
