# Generated by Django 5.2.9 on 2026-01-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_add_refund_and_payment_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Indirizzo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Città'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_country',
            field=models.CharField(default='Italia', max_length=100, verbose_name='Nazione'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Intestatario'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_pec',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='PEC'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_province',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_sdi',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Codice SDI'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_vat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='P.IVA / Codice Fiscale'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot_count',
            field=models.PositiveIntegerField(default=1, help_text='Numero di slot consecutivi da 30 minuti. Prezzo: €60 × numero slot.', verbose_name='Numero slot'),
        ),
    ]
