# Generated by Django 5.2.9 on 2026-01-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_add_refund_and_payment_token_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot_count',
            field=models.PositiveIntegerField(default=1, help_text='Numero di slot consecutivi da 30 minuti. Prezzo: €60 × numero slot.', verbose_name='Numero slot'),
        ),
    ]
