# Generated by Django 5.2.9 on 2025-12-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointmentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('in_person', 'In presenza'), ('video', 'Videochiamata')], default='in_person', max_length=20, verbose_name='Tipo consulenza'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='videocall_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Codice videochiamata'),
        ),
    ]
