# Generated by Django 5.2.9 on 2026-01-01 17:31

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_consultation_type_and_videocall'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_uid', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='UID Google')),
                ('summary', models.CharField(max_length=255, verbose_name='Titolo')),
                ('start_datetime', models.DateTimeField(verbose_name='Inizio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fine')),
                ('synced_at', models.DateTimeField(verbose_name='Ultima sincronizzazione')),
            ],
            options={
                'verbose_name': 'Evento Google Calendar',
                'verbose_name_plural': 'Eventi Google Calendar',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='appointmentattachment',
            name='appointment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='booking.appointment', verbose_name='Appuntamento'),
        ),
    ]
