# Generated by Django 5.2.9 on 2026-01-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_consultation_type_and_videocall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(verbose_name='Note'),
        ),
    ]
