# Generated by Django 5.2.9 on 2026-01-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_appointment_notes'),
        ('booking', '0005_google_calendar_event'),
    ]

    operations = [
    ]
