# Generated by Django 5.2.9 on 2026-01-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_merge_20260101_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot_count',
            field=models.PositiveIntegerField(default=1, help_text='Numero di slot consecutivi da 30 minuti', verbose_name='Numero slot'),
        ),
    ]
