# Generated by Django 5.2.9 on 2025-12-31 02:38

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomiciliazioniPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
                ('service_description', wagtail.fields.RichTextField(blank=True, verbose_name='Descrizione servizio')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, verbose_name='Testo ringraziamento')),
                ('tribunali', models.TextField(blank=True, help_text='Uno per riga', verbose_name='Tribunali coperti')),
            ],
            options={
                'verbose_name': 'Pagina Domiciliazioni',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DomiciliazioniFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='domiciliazioni.domiciliazionipage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomiciliazioniSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField()),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('nome_avvocato', models.CharField(max_length=200, verbose_name='Nome Avvocato')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tribunale', models.CharField(max_length=100, verbose_name='Tribunale')),
                ('tipo_udienza', models.CharField(max_length=100, verbose_name='Tipo udienza')),
                ('data_udienza', models.DateField(verbose_name='Data udienza')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='domiciliazioni.domiciliazionipage')),
            ],
            options={
                'verbose_name': 'Richiesta domiciliazione',
                'verbose_name_plural': 'Richieste domiciliazione',
                'ordering': ['-submit_time'],
            },
        ),
        migrations.CreateModel(
            name='DomiciliazioniDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='domiciliazioni/%Y/%m/', verbose_name='Documento')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='domiciliazioni.domiciliazionisubmission')),
            ],
            options={
                'verbose_name': 'Documento allegato',
                'verbose_name_plural': 'Documenti allegati',
            },
        ),
    ]
