# Generated by Django 5.2.9 on 2026-01-02
# Consolidated migration for domiciliazioni app

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomiciliazioniPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
                ('service_description', wagtail.fields.RichTextField(blank=True, verbose_name='Descrizione servizio')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, verbose_name='Testo ringraziamento')),
                ('tribunali', models.TextField(blank=True, help_text='Uno per riga', verbose_name='Tribunali coperti')),
            ],
            options={
                'verbose_name': 'Pagina Domiciliazioni',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DomiciliazioniFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='domiciliazioni.domiciliazionipage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomiciliazioniSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('nome_avvocato', models.CharField(max_length=200, verbose_name='Nome e Cognome Avvocato')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tribunale', models.CharField(choices=[('roma', 'Tribunale di Roma'), ('corte_appello', "Corte d'Appello di Roma"), ('gdp', 'Giudice di Pace di Roma'), ('tar', 'TAR Lazio'), ('unep', 'Ufficio UNEP di Roma')], max_length=100, verbose_name='Tribunale')),
                ('tipo_udienza', models.CharField(choices=[('civile', 'Udienza Civile'), ('penale', 'Udienza Penale'), ('lavoro', 'Udienza Lavoro'), ('famiglia', 'Udienza Famiglia'), ('esecuzioni', 'Esecuzioni'), ('fallimentare', 'Fallimentare'), ('volontaria', 'Volontaria Giurisdizione'), ('notificazioni', 'Ufficio notificazioni'), ('esecuzione_protesti', 'Ufficio esecuzione e protesti'), ('altro', 'Altro')], default='civile', max_length=100, verbose_name='Tipo udienza')),
                ('data_udienza', models.DateField(blank=True, null=True, verbose_name='Data udienza')),
                ('note', models.TextField(blank=True, verbose_name='Note e istruzioni')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='domiciliazioni.domiciliazionipage')),
                ('attivita_richieste', models.TextField(blank=True, help_text='Descrivi le attività da svolgere in udienza (es: mera comparizione, deposito atti, richiesta rinvio)', verbose_name='Attività richieste')),
                ('esito_udienza', models.TextField(blank=True, verbose_name='Esito udienza')),
                ('giudice', models.CharField(blank=True, max_length=100, verbose_name='Giudice')),
                ('numero_rg', models.CharField(default='', help_text='Numero di Ruolo Generale (es: 1234/2025)', max_length=50, verbose_name='Numero R.G.')),
                ('ora_udienza', models.TimeField(blank=True, null=True, verbose_name='Ora udienza')),
                ('ordine_appartenenza', models.CharField(blank=True, max_length=100, verbose_name='Ordine di appartenenza')),
                ('parti_causa', models.TextField(blank=True, help_text='Attore vs Convenuto', verbose_name='Parti in causa')),
                ('sezione', models.CharField(blank=True, help_text='Es: Sezione Civile, Sezione Lavoro', max_length=50, verbose_name='Sezione')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('accepted', 'Accettata'), ('completed', 'Completata'), ('cancelled', 'Annullata')], default='pending', max_length=20, verbose_name='Stato')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Richiesta domiciliazione',
                'verbose_name_plural': 'Richieste domiciliazione',
                'ordering': ['-submit_time'],
            },
        ),
        migrations.CreateModel(
            name='DomiciliazioniDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='domiciliazioni/%Y/%m/', verbose_name='Documento')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='domiciliazioni.domiciliazionisubmission')),
            ],
            options={
                'verbose_name': 'Documento allegato',
                'verbose_name_plural': 'Documenti allegati',
            },
        ),
    ]
