# Generated by Django 5.2.9 on 2026-01-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domiciliazioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domiciliazionisubmission',
            name='tipo_udienza',
            field=models.CharField(default='civile', max_length=100, verbose_name='Tipo udienza'),
        ),
        migrations.AlterField(
            model_name='domiciliazionisubmission',
            name='tribunale',
            field=models.CharField(max_length=100, verbose_name='Tribunale'),
        ),
    ]
