# Generated by Django 5.2.9 on 2025-12-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domiciliazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='attivita_richieste',
            field=models.TextField(blank=True, help_text='Descrivi le attività da svolgere in udienza (es: mera comparizione, deposito atti, richiesta rinvio)', verbose_name='Attività richieste'),
        ),
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='esito_udienza',
            field=models.TextField(blank=True, verbose_name='Esito udienza'),
        ),
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='giudice',
            field=models.CharField(blank=True, max_length=100, verbose_name='Giudice'),
        ),
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='numero_rg',
            field=models.CharField(default='', help_text='Numero di Ruolo Generale (es: 1234/2025)', max_length=50, verbose_name='Numero R.G.'),
        ),
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='ora_udienza',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora udienza'),
        ),
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='ordine_appartenenza',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ordine di appartenenza'),
        ),
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='parti_causa',
            field=models.TextField(blank=True, help_text='Attore vs Convenuto', verbose_name='Parti in causa'),
        ),
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='sezione',
            field=models.CharField(blank=True, help_text='Es: Sezione Civile, Sezione Lavoro', max_length=50, verbose_name='Sezione'),
        ),
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('accepted', 'Accettata'), ('completed', 'Completata'), ('cancelled', 'Annullata')], default='pending', max_length=20, verbose_name='Stato'),
        ),
        migrations.AddField(
            model_name='domiciliazionisubmission',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='domiciliazionisubmission',
            name='data_udienza',
            field=models.DateField(blank=True, null=True, verbose_name='Data udienza'),
        ),
        migrations.AlterField(
            model_name='domiciliazionisubmission',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='domiciliazionisubmission',
            name='nome_avvocato',
            field=models.CharField(max_length=200, verbose_name='Nome e Cognome Avvocato'),
        ),
        migrations.AlterField(
            model_name='domiciliazionisubmission',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note e istruzioni'),
        ),
        migrations.AlterField(
            model_name='domiciliazionisubmission',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='domiciliazioni.domiciliazionipage'),
        ),
        migrations.AlterField(
            model_name='domiciliazionisubmission',
            name='tipo_udienza',
            field=models.CharField(choices=[('civile', 'Udienza Civile'), ('penale', 'Udienza Penale'), ('lavoro', 'Udienza Lavoro'), ('famiglia', 'Udienza Famiglia'), ('esecuzioni', 'Esecuzioni'), ('fallimentare', 'Fallimentare'), ('volontaria', 'Volontaria Giurisdizione'), ('altro', 'Altro')], default='civile', max_length=100, verbose_name='Tipo udienza'),
        ),
        migrations.AlterField(
            model_name='domiciliazionisubmission',
            name='tribunale',
            field=models.CharField(choices=[('lecce', 'Tribunale di Lecce'), ('brindisi', 'Tribunale di Brindisi'), ('taranto', 'Tribunale di Taranto'), ('bari', 'Tribunale di Bari')], max_length=100, verbose_name='Tribunale'),
        ),
    ]
