# Generated by Django 5.2.9 on 2026-01-03 09:50

import sld_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domiciliazioni', '0002_alter_domiciliazionisubmission_tipo_udienza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domiciliazionidocument',
            name='file',
            field=models.FileField(upload_to='domiciliazioni/%Y/%m/', validators=[sld_project.validators.FileValidator()], verbose_name='Documento'),
        ),
    ]
