# Generated by Django 5.2.9 on 2026-01-02
# Consolidated migration for home app

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_text', wagtail.fields.RichTextField(blank=True, verbose_name='Testo')),
                ('about_title', models.CharField(default='LO STUDIO', max_length=100, verbose_name='Titolo Chi Siamo')),
                ('cta_button_text', models.CharField(default='Prenota appuntamento', max_length=50, verbose_name='Pulsante')),
                ('cta_button_url', models.CharField(default='/prenota/', max_length=200, verbose_name='URL')),
                ('cta_text', models.CharField(blank=True, max_length=200, verbose_name='Testo CTA')),
                ('cta_title', models.CharField(default='TI ASCOLTIAMO', max_length=100, verbose_name='Titolo CTA')),
                ('hero_accent', models.CharField(default='GIUSTIZIA.', max_length=100, verbose_name='Testo accent')),
                ('hero_description', wagtail.fields.RichTextField(blank=True, verbose_name='Descrizione')),
                ('hero_location', models.CharField(default='• Lecce', max_length=100, verbose_name='Location')),
                ('hero_subtitle', models.CharField(default='AVVOCATO', max_length=200, verbose_name='Sottotitolo')),
                ('services_subtitle', models.CharField(blank=True, max_length=200, verbose_name='Sottotitolo')),
                ('services_title', models.CharField(default='AREE DI PRATICA', max_length=100, verbose_name='Titolo Servizi')),
                ('hero_line1', models.CharField(default='ASSISTENZA LEGALE', max_length=100, verbose_name='Riga 1 (nera)')),
                ('hero_line2', models.CharField(default='PER UNA TUTELA', max_length=100, verbose_name='Riga 2 (nera)')),
                ('hero_line3', models.CharField(default='DI ELEVATA EFFICACIA', max_length=100, verbose_name='Riga 3 (magenta)')),
                ('hero_line4', models.CharField(default='E COMPETENZA', max_length=100, verbose_name='Riga 4 (magenta)')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Homepage',
            },
            bases=('wagtailcore.page',),
        ),
    ]
