# Generated by Django 5.2.9 on 2026-01-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_subtitle',
            new_name='hero_txt_studio',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_accent',
            new_name='hero_txt_accent',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_txt_legale',
            field=models.CharField(blank=True, max_length=200, verbose_name='Footer: Note'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_txt_studio',
            field=models.CharField(default='STUDIO LEGALE', max_length=200, verbose_name='Footer: STUDIO LEGALE'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_txt_accent',
            field=models.CharField(default="D'ONOFRIO", max_length=100, verbose_name='Footer: Cognome (con apostrofo)'),
        ),
    ]
