# Generated by Django 5.2.9 on 2026-01-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_hero_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_txt_accent',
            field=models.CharField(default="D'ONOFRIO", max_length=100, verbose_name='Footer: Riga 3 (bianco + apostrofo accent)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_txt_legale',
            field=models.CharField(default='LEGALE', max_length=200, verbose_name='Footer: Riga 2 (grigio)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_txt_studio',
            field=models.CharField(default='STUDIO', max_length=200, verbose_name='Footer: Riga 1 (grigio)'),
        ),
    ]
