# Generated by Django 5.2.9 on 2025-12-31 02:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Testo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='LO STUDIO', max_length=100, verbose_name='Titolo Chi Siamo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_text',
            field=models.CharField(default='Prenota appuntamento', max_length=50, verbose_name='Pulsante'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_url',
            field=models.CharField(default='/prenota/', max_length=200, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Testo CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(default='PARLIAMO', max_length=100, verbose_name='Titolo CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_accent',
            field=models.CharField(default='GIUSTIZIA.', max_length=100, verbose_name='Testo accent'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_location',
            field=models.CharField(default='Lecce • Martina Franca', max_length=100, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default="AVVOCATO", max_length=200, verbose_name='Sottotitolo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='STUDIO LEGALE', max_length=200, verbose_name='Titolo Hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sottotitolo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='AREE DI PRATICA', max_length=100, verbose_name='Titolo Servizi'),
        ),
    ]
