# Generated by Django 5.2.9 on 2026-01-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_hero_txt_accent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='AREE DI ATTIVITÀ', max_length=100, verbose_name='Titolo Servizi'),
        ),
    ]
