# Generated by Django 5.2.9 on 2026-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_about_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_location',
            field=models.CharField(default='• Lecce', max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.TextField(default='ASSISTENZA LEGALE\nPER UNA TUTELA\nDI ELEVATA EFFICACIA\nE COMPETENZA', verbose_name='Titolo Hero'),
        ),
    ]
