# Generated by Django 5.2.9 on 2026-01-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_hero_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_line1',
            field=models.CharField(default='ASSISTENZA LEGALE', max_length=100, verbose_name='Riga 1 (nera)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_line2',
            field=models.CharField(default='PER UNA TUTELA', max_length=100, verbose_name='Riga 2 (nera)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_line3',
            field=models.CharField(default='DI ELEVATA EFFICACIA', max_length=100, verbose_name='Riga 3 (magenta)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_line4',
            field=models.CharField(default='E COMPETENZA', max_length=100, verbose_name='Riga 4 (magenta)'),
        ),
    ]
